### ISSUE TITLE
Passing Data between two pages

### ISSUE THREAD

**Issue by Aidan-V** [CSAllenISD/2023-ISP-Bug-Tracker#13]
Need to figure out how to pass data to another file using reactJS in a non-complicated way.

**Comment by Rafid-A** [comment]
React Router DOM is an option but it is decently hard to understand/learn

**Comment by Aidan-V** [comment]
We understand DOM now, using the useStates both true and false allows for the root element to the dropdown box, in which the tree would expand into such useStates.

**Comment by Brook-A-CS** [comment]
I was able to do this by adding the data to the highest level file it was necessary in, then passing it as a function parameter to the other files.


 
![week of feb 15 website directory structure drawio](https://user-images.githubusercontent.com/70398321/219153622-5b45c328-c709-43a9-b3cf-0230a414d1b5.png)


This is the "tree" of our website. Although it is not strictly defined, each arrow represents a function call. For adding an Issue I created the data var in the App,jsx file because it allowed me to pass it to both views below it.
